### ISSUE TITLE
ECMWF level zero is set to incorrect parameters

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#13]
For the ECMWF processing (including ERA5) the top layer is set to an incorrect value, rendering the results inaccurate.

**Comment by adamcpovey** [comment]
Could you be a tad more precise? I remember being careful about the top and bottom levels so I'm curious what I misunderstood (or changed between versions, as I didn't check the changelog exhaustively).

**Comment by simonrp84** [comment]
Sorry, wrote it in a rush. The top level of the atmosphere is set to zero pressure, which is not realistic. This seems to come from the avec and bvec having values of 0 in the first index of their arrays (each array is len=138, it should be 137 with the first value gone). I tried to change this but that screwed up RTTOV, so not as simple as deleting the first values and going with that.
I do plan to look at this, but it probably won't be any time soon.

**Comment by w-k-jones** [comment]
Hi Simon,


The avec and bvec values should give the half level pressures, so the top level pressure should in fact be the average of the pressures given by the 1st and 2nd avec, bvec values. Not sure if this would work with the code, but is ho it should be according to the ERA definitions (https://www.ecmwf.int/en/forecasts/documentation-and-support/60-model-levels)


Cheers, Will

________________________________

**Comment by simonrp84** [comment]
I'm not convinced that what we're doing in ORAC is right, but I'm closing this issue as it makes no difference to the output (unless we get a cloud at 1Hpa).
