### ISSUE TITLE
Wiki missing links

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#15]
This page on the wiki points to non-existent files...does anyone know where they went?
https://github.com/ORAC-CC/orac/wiki/Information

**Comment by caropoulsen** [comment]
no idea where the links went but probably best to point to the relevant CCI documentation

for cloud

http://www.esa-cloud-cci.org/?q=documentation


________________________________

**Comment by adamcpovey** [comment]
Sod knows where those files went, but they're definitely not on the SVN.

I've updated the links on this page to point to the CCI User Guides. None of these links are permanent, though I've heard that ESA are working out a DOI system for such things.

A larger question: Should this page be merged with [this](../wiki/Products)? Seems like a better place for it.

**Comment by simonrp84** [comment]
Yes merging would be a good idea - the products page should also be renamed to something like "existing ORAC products" or something. We can then create another page that describes the actual ORAC processor output, right now it's not immediately clear that there is 'ORAC the data processor' and also 'ORAC CCI products'.

**Comment by adamcpovey** [comment]
Pages merged and links updated, though we will need to keep an eye out for ESA migrating it's sites.
