### ISSUE TITLE
Documentation for pre-proc options.

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#17]
I hae updated the wiki to describe all the pre-processor options that I know, but two need some info:
https://github.com/ORAC-CC/orac/wiki/Introduction
Could someone who knows what they are please add descriptions for USE_SWANSEA_CLIMATOLOGY and SWANSEA_GAMMA?

Assigning Adam as it seems like an Aerosol thing...

**Comment by adamcpovey** [comment]
Details duly updated.
