### ISSUE TITLE
Formatting of variables names and metadata

### ISSUE THREAD

**Issue by adamcpovey** [ORAC-CC/orac#2]
[Continuation of http://proj.badc.rl.ac.uk/orac/ticket/77] The variables names output by ORAC by default conform to the standards required by none of the groups that seek our data.

Everyone has slightly different requirements and, so far, we've agreed that re-formatting files is best left to ad hoc processing. However, it would be useful for the default output to conform to *something*. Being fully NC-compliant is one idea.

**Comment by gmcgarragh** [comment]
I thought that we have tried to be NC-compliant for years.

Anyway, with a system as diverse as ORAC we cannot worry about multiple compliances.

But, if this was serious issue we could create a configuration file that contains these details.  Then we would have an NC-compliant configuration file as default and then users could use other configurations files for other standards using the NC-compliant configuration file as a template.

**Comment by adamcpovey** [comment]
@gmcgarragh has been borne out by practice - we just write a script to change the formatting to whatever our the deliverable requires. There is certainly room to tidy things in there, but there isn't need to overhaul anything.
