### ISSUE TITLE
Relative Azimuth Angle issues

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#20]
We need to ensure that the relative azimuth angle convention used in ORAC is consistent. It *should* be as follows:
- Sun + Satellite in same location: RAA = 0
- Sun + Satellite on opposite sides of pixel: RAA = 180

We need to check that each sensors follows the convention above. A list of sensors is below, once you have checked that the RAA is correct for that sensor then please tick it off:

- [x] AATSR
- [ ] ABI
- [x] AGRI
- [x] AHI
- [x] ATSR2
- [x] AVHRR
- [x] MODIS
- [x] SEVIRI
- [x] SLSTR
- [ ] VIIRS-M
- [ ] VIIRS-I

I will also check: ABI, VIIRS.

Others, please assign yourself to check: AATSR, ATSR2, AVHRR, MODIS, SLSTR.

**Comment by adamcpovey** [comment]
Done for ATSR and MODIS. Will now move on to the surface routines.

Considering our AVHRR format is not a standard release, we need someone who knows how to generate those files to check what's going on there. (It'd also be nice to document in this Wiki how they're made.)

**Comment by garethethomas** [comment]
Hi Adam

Were any changes required? If so, what?

Cheers

Gareth

**Comment by adamcpovey** [comment]
Commits 697a8ab6ca9c301195075ad940e7ac6b1592b53a and a988d22ebfdbf9eb402b3ecb7a5d863410a58d62, as both had the angles the opposite way around to Don's definition. However, since we're beginning to suspect that the definition is also the other way around in DISORT, they were likely correct in practice.

**Comment by adamcpovey** [comment]
I've done AVHRR. I would prefer not to do the A*I sensors or VIIRS as those require me finding data to run in the first place.
