### ISSUE TITLE
surface reflectance possibly not correct bug in cox and munk

### ISSUE THREAD

**Issue by caropoulsen2** [ORAC-CC/orac#21]
Surface leaving flux product comparison with CERES indicates that AATSR surface leaving reflectance is too low. This could be related to the angle definition problem so should be checked after that is assessed.

Caroline

**Comment by adamcpovey** [comment]
@caropoulsen2 It might be worth re-checking this once we've merged in my recent changes and moved to RTTOV 13.

Also, I have been talking to Andy Sayer about the Cox-Munk implementation. I [noticed that our reflectance](http://eodg.atm.ox.ac.uk/eodg/gray/2020Povey_relative-azimuth-surface.pdf) at 1.6um is now zero. He commented,

> I agree that reflectance at 1.6 microns should not be 0. So I am also not sure why that change would have been made from the references I use. More recent measurements suggest that you can model the spectral dependence of whitecaps as a polynomial on log (water absorption coefficient) - see Equation 7 in this paper: https://www.frontiersin.org/articles/10.3389/feart.2019.00014/full I am considering moving toward something like this, i.e. set the absolute reflectance at some wavelength as is done historically but then use this polynomial for spectral dependence. I would also consider updating the whitecap fraction model from the 1980 one to a newer one: there are more measurements now and still an order of magnitude variability. I like this paper because it is measurements from a ship as opposed to a coastal platform (see Fig 3): https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2008GL036165

@gmcgarragh and @garethethomas - you two have much more invested in that model than I do. Any opinions? (I haven't read either paper yet.)
