### ISSUE TITLE
Replace USGS land-cover data

### ISSUE THREAD

**Issue by adamcpovey** [ORAC-CC/orac#3]
[Continuation of http://proj.badc.rl.ac.uk/orac/ticket/107] The current external land-cover mask has insufficient resolution and lacks many important islands (e.g. Hawaii). An alternative should be implemented.

**Comment by simonrp84** [comment]
We already have this through some of my work last year. I thought I'd sent a msg round about it but I guess not. Will do so when I'm back in the office on the 23rd.

**Comment by adamcpovey** [comment]
I know you added the ability to read a land/sea mask file for the geostationary satellites, but the default processing chain still uses the USGS file (and it's not obvious where an external user would obtain the necessary files). As we know of problems that result from using the USGS, I'm inclined to remove it entirely once a replacement that works for all platforms is put in place.

**Comment by caropoulsen** [comment]
Hi Adam,

Quite happy to have an improved land cover  map has anyone considered the CCI land cover map.
https://www.esa-landcover-cci.org/
This is the map we are being encouraged to used by ESA however I know very little about the quality.
We should keep the USGS land cover map capability though and create a link to where is can be found, perhaps DWD can help with that aspect.

Caroline

**Comment by simonrp84** [comment]
I made a drop-in replacement, which is on the CEMS servers somewhere. I sent a mail about it last year, but can't find it now (thanks, Nexus365!)

When I'm back in the office next week I'll dig it out and send another email around.


Cheers,

Simon


________________________________

**Comment by simonrp84** [comment]
Hi all,
The drop-in replacement (at very high res) is available here for AOPP users:
/network/aopp/apres/users/proud/ORAC_Data/global_lsm.nc

And for CEMS/CEDA/Jasmin/RAL it's here:
/group_workspaces/jasmin2/cloud_ecv/data_in2/global_lsm.nc

Ideally it'd be good to get this on an external server. I have asked physics IT for some space to host it

**Comment by gmcgarragh** [comment]
Given that there is required and test data in BADC svn, LUTs on the EODG website, and now this file in another place I figure thoughts on a central data repository would be good.  Can Ox Physics host that?

**Comment by simonrp84** [comment]
Hi Greg,
 I have already asked about this, we should have some web space available to us sometime next week.

Cheers,
Simon

Sent from my iPad

On 28 Apr 2018, at 18:00, Greg McGarragh <notifications@github.com<mailto:notifications@github.com>> wrote:

Given that there is required and test data in BADC svn, LUTs on the EODG website, and now this file in another place I figure thoughts on a central data repository would be good. Can Ox Physics host that?
