### ISSUE TITLE
2 Issues in ReadDriver.F90

### ISSUE THREAD

**Issue by w-k-jones** [ORAC-CC/orac#4]
Hi all,

Discovered a couple of bugs with ReadDriver.F90 yesterday while setting up some retrievals, have detailed them below:

1. If CTRL%LUTClass is set in the driver file, ReadDriver raises an error message at line 1967: "ERROR: Read_Driver(): Unknown option: CTRL%LUTCLass"
This occurs during the processing of optional driver file inputs, as CTRL%LUTClass is not included in the list of arguments to ignore (L1955-1963). Issue is fixed by including it in this list.

2. CTRL%Process_Cloudy_Only is parsed after it's effects are processed. This means that the driver file input is ignored, as Ntypes_to_process and types_to_process are set using the default value (.true.). I'm not sure on the best way to fix this, as the effects (around line 630) are processed well before the driver option is parsed (~1900). Being able to set this value as .false. in order to retrieve clear sky surface temeprature retrievals is important for reducing long wave bias in the broadband fluxes output.

Cheers, Will

**Comment by adamcpovey** [comment]
As it's name implies, `old_driver_*_read()` is the old way of reading driver files and tends to suffer code rot as it requires manual maintenance. As far as I can tell, neither of your problems occur with the new format driver file. I'll update the Wiki to describe the new format.

Regardless, there are simple fixes for both of those problems. I'll commit them when I finish some other work.

**Comment by w-k-jones** [comment]
Quick update as this is another issue relating to ReadDriver:

At L861 it says "Fr uses SelmMeas" however, below this Ctrl%FG(IFr,:) is set by default to SelmCtrl, and instead IPc is set to SelmMeas. Is this a bug? The settings for Ctrl%AP have them the other way round.

**Comment by caropoulsen** [comment]
Looks like a bug to me, good spot, in theory it should not make much difference as Apriori uncertainty is very large but might make a small improvement in practice

IPc should be Selmeas- this means the matching temperature is used as first guess and Apriori

Caroline

**Comment by caropoulsen** [comment]
Yes you are correct, and so should be kept the same iFr though could have apriori info e.g from subpixel cloud, but in practice we do not use it.
