### ISSUE TITLE
local_defaults.py needs updating

### ISSUE THREAD

**Issue by dr1315** [ORAC-CC/orac#62]
Current version of `local_defaults.py` in _orac/tools/pyorac/_ has not been updated for new` ecmwf_flag` format. Needs to be updated as currently need to set the ERA-Interim directory paths (lines 56-60 in `local_defaults.py`) to be the same as ERA5 path (lines 65-66 in `local_defaults.py`).

**Comment by dr1315** [comment]
NB// This is for main branch

**Comment by adamcpovey** [comment]
Is this alright now?
