### ISSUE TITLE
gfortran_linux-64 defaults to anaconda in current version

### ISSUE THREAD

**Issue by dr1315** [ORAC-CC/orac#65]
When building conda env, `gfortran_linux-64` defaults to anaconda channel rather than conda-forge.

**Comment by simonrp84** [comment]
Are you using `conda config --set channel_priority strict`?

**Comment by dr1315** [comment]
Just fixing it with Adam and decided that removing `-anaconda` from the channels list in the `dependecies.nompi.yml` file fixed the problem.

**Comment by simonrp84** [comment]
@dr1315  Has this been solved?

**Comment by adamcpovey** [comment]
I appear to have removed the offending lines from the dependencies files.

**Comment by simonrp84** [comment]
Closing this one then, @dr1315 reopen if necessary (and/or you still care ;-) )
