### ISSUE TITLE
Delete old driver read routines

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#7]
The main orac processor contains routines to read both old and new driver file formats in ./src/ReadDriver.F90:
subroutine old_driver_first_read()
subroutine old_driver_second_read()

These seem superfluous as the new routines are available and it seems these are widely used. I therefore propose to delete the old routines to tidy the file up and prevent code rot. 

Does anyone have objections to this?

**Comment by caropoulsen** [comment]
I am still using old  routines please do not delete quite yet.

________________________________

**Comment by simonrp84** [comment]
Ok. I think it's quite important to remove rotting code, so can we set a date to move to the new driver format, either through updating your scripts or using Adam's scripts?
I suggest 28th Sept!

**Comment by caropoulsen** [comment]
agreed

**Comment by simonrp84** [comment]
I have removed the old routines in today's commit, 5745f33. Once you update to the latest version of the code you will *NOT* be able to use the old read driver routines.
