### ISSUE TITLE
pyorac cannot read in MODIS emissivity

### ISSUE THREAD

**Issue by dr1315** [ORAC-CC/orac#78]
When building the pre-processor driver in pyorac, if MODIS emissivity data is selected, `tools/pyorac/drivers.py` will set `emis` variable to `None` at line 70, rather than assign correct path.

See:
https://github.com/ORAC-CC/orac/blob/ea56acccf267a249c60802b9eae6743e605d135f/tools/pyorac/drivers.py#L70

**Comment by adamcpovey** [comment]
No, that's how it's supposed to work. `use_modis_emis_in_rttov` is [a binary flag](https://github.com/ORAC-CC/orac/blob/ea56acccf267a249c60802b9eae6743e605d135f/pre_processing/orac_preproc.F90#L472). It triggers an override of the emissivity field with that from MODIS CIMSS monthly values [here](https://github.com/ORAC-CC/orac/blob/ea56acccf267a249c60802b9eae6743e605d135f/pre_processing/rttov_driver.F90#L807).
