### ISSUE TITLE
Where to find ORAC lookup tables

### ISSUE THREAD

**Issue by pdebuyl** [ORAC-CC/orac#90]
The wiki page https://github.com/ORAC-CC/orac/wiki/Download-LUTs points to the URL http://eodg.atm.ox.ac.uk/user/mcgarragh/orac_luts/ to download LUTs. When following the link, I have an error 403.

Is there another location to download LUTs?

Thanks,

Pierre

**Comment by andyprata** [comment]
Hi Pierre

Yes that link needs updating. You can find the latest look-up tables here: https://gws-access.jasmin.ac.uk/public/oracluts/

As a general rule, you should use the latest version of the LUT for the sensor you're interested in. However, there are few tables in there that are experimental. The uncertainty treatment for the solar channels is also currently being developed.

May I ask what you plan to use them for? (i.e. cloud, volcanic ash? which sensor etc?)

I could potentially advise on the best way forward then.

Cheers
Andy

**Comment by pdebuyl** [comment]
Hello @andyprata thanks for the reply :-)

I now have the NetCDF LUT files for SEVIRI. I guess that I have mixed up something though: the `orac.py` driver program complained about not finding "sad files" which are the the `orac_luts` subdirectory by default, hence my request for LUT files.

Are the `.sad` and `.nc` files providing similar information here?

Regarding the use: our (i.e. colleagues in the remote sensing team at RMIB) first use is for cloud retrieval with SEVIRI, with a focus on ice clouds.

**Comment by simonrp84** [comment]
Hi Pierre, good to see you getting started on ORAC!

Just to note that the netCDF lookup tables are experimental right now and, at least in my tests, the uncertainties for SEVIRI are problematic.
As such, I'll send you the old (`.sad`) format LUTs via slack. 

Regarding the `orac.py` program, that's @adamcpovey's script. Am sure he can point you at what option is needed to run with whichever version of the LUTs you choose.

**Comment by pdebuyl** [comment]
Thanks @simonrp84 :-)

**Comment by adamcpovey** [comment]
There are two reasons that that script might complain: the files you want aren't in the folder (which is solved by accessing the sources above) or the code doesn't know about the LUT you want to use. This is true of the NCDF tables, as they're experimental so we haven't entirely decided what they look like. The table definitions [are here](https://github.com/ORAC-CC/orac/blob/150d16e1570176e81e59692911d47778f2303246/tools/pyorac/definitions.py#L649) and, if that's what you need, I can copy over the syntax for a new table in the morning when I'm at my desk.

**Comment by pdebuyl** [comment]
Hello @andyprata @adamcpovey . I could get a copy of SAF files for MSG3 and will try to start from there. I am not really enthusiastic about using experimental definition files so will try to stick with those files.

**Comment by pdebuyl** [comment]
How much storage would be needed?

**Comment by adamcpovey** [comment]
Absolutely every table I have (which will include some repeats, failed experiments, and very old versions) is 51GB. So a 100GB space should cover everything we would ever want and we'd have to have a chat to work out the minimum necessary space.
