### ISSUE TITLE
Which ECMWF data set / file / version to use?

### ISSUE THREAD

**Issue by pdebuyl** [ORAC-CC/orac#91]
Hello,

I'd like to know which ECMWF data to download for `NWP_FLAG = 1`. Do you have a sample MARS request?

**Comment by simonrp84** [comment]
Hi Pierre, see the attached zip for two scripts I've previously used for retrieving ERA5 data from MARS for use with `NWP_FLAG = 1`.
Bear in mind this script is a little bit old (and itself a derivative of one supplied by the NWC-SAF) so it will probably require some updates before it runs.

[ERA.zip](https://github.com/ORAC-CC/orac/files/13650240/ERA.zip)

**Comment by simonrp84** [comment]
Also, looking at the script itself I suspect it may be for retrieving data from the operational forecast stream rather than ERA5 ;-) But that should be easy to fix.

**Comment by pdebuyl** [comment]
Thanks a lot for the support @simonrp84 :-) Will test this soon!

**Comment by pdebuyl** [comment]
If that is useful to anyone, I put it together as a single python file. I had to change the parameter numeric values. I put the filename that ORAC expects from me as far as I can understand.
[get_ecmwcf_netcdf_for_orac.py.gz](https://github.com/ORAC-CC/orac/files/13684444/get_ecmwcf_netcdf_for_orac.py.gz)

**Comment by pdebuyl** [comment]
Call as `python get_ecmwcf_netcdf_for_orac.py 2023-08-25 00` for instance.

**Comment by pdebuyl** [comment]
Closing, this is addressed.

**Comment by simonrp84** [comment]
Sorry, this slipped my mind in the rather hectic last month! Glad you found the data in the end!
